package constants

var TotalConstants = map[string]string {
	"Common_Calc": "Рассчитать",
	"Common_Comment": "Комментарий",
	"Common_Create": "Создать",
	"Common_DateGToday": "Дата должна быть больше сегодняшнего дня",
	"Common_Delete": "Удалить",
	"Common_Save": "Сохранить",
	"Common_Search": "Поиск",
	"Common_ValueG0": "Значение должно быть больше нуля",
	"Finance_BondCd": "КД, руб.",
	"Finance_BondCdCount": "Количество выплат КД",
	"Finance_BondCurrentPrice": "Текущая цена, руб.",
	"Finance_BondMaturityDate": "Дата погашения облигации",
	"Finance_BondNcd": "НКД, руб.",
	"Finance_BondSum": "Сумма приобретения, руб.",
	"Finance_DaysToMaturity": "Дней до погашения",
	"Finance_DiffSum": "Разница, руб.",
	"Finance_Nominal": "Номинал, руб.",
	"Finance_TotalBoughtCnt": "Количество купленных облигаций",
	"Finance_TotalBoughtSum": "Сумма купленных облигаций, руб.",
	"Finance_TotalSum": "Итоговая сумма, руб.",
	"Finance_YTM": "Доходность к погашению, %г.",
	"Food_Brand": "Бренд",
	"Food_C": "К",
	"Food_CPFC": "КБЖУ, 100г.",
	"Food_Cal100": "ККал, 100г.",
	"Food_Carb100": "Углеводы, 100г.",
	"Food_Cb": "У",
	"Food_F": "Ж",
	"Food_Fat100": "Жиры, 100г.",
	"Food_Name": "Наименование",
	"Food_NotFound": "Еда не найдена",
	"Food_P": "Б",
	"Food_Prot100": "Белки, 100г.",
	"Menu_Activity": "Активность",
	"Menu_Activity_Journal": "Журнал активности",
	"Menu_Activity_SportList": "Управление спортом",
	"Menu_Activity_Stats": "Статистика",
	"Menu_Finance": "Финансы",
	"Menu_Finance_BondCalc": "Расчет доходности облигаций",
	"Menu_Food": "Еда",
	"Menu_Food_FoodList": "Управление едой",
	"Menu_Food_Journal": "Журнал приема пищи",
	"Menu_Food_Stats": "Статистика",
	"Menu_Settings": "Настройки",
	"Menu_Settings_CalcCal": "Расчет лимита ккал.",
	"Menu_Settings_User": "Пользователь",
	"Menu_Weight": "Вес",
	"Menu_Weight_Stats": "Статистика",
	"Menu_Weight_WeightList": "Вес тела",
	"Page_Finance_BondCalc": "Расчет доходности облигаций",
	"Page_Food_FoodEdit": "Редактирование еды",
	"Page_Food_FoodList": "Управление едой",
	"Page_Main": "Главная страница",
	"Page_NotFound": "Страница не найдена",
	"Page_Settings_CalcCal": "Расчет лимита ккал.",
	"Settings_Activity1": "Сидячая активность",
	"Settings_Activity2": "Легкая активность",
	"Settings_Activity3": "Средняя активность",
	"Settings_Activity4": "Полноценная активность",
	"Settings_Activity5": "Cупер активность",
	"Settings_Age": "Возраст, лет",
	"Settings_Gender": "Пол",
	"Settings_GenderF": "Женский",
	"Settings_GenderM": "Мужской",
	"Settings_Height": "Рост, см.",
	"Settings_Ubm": "Уровень базального метаболизма, ккал.",
	"Settings_Weight": "Вес, кг.",
}
